name: treegraph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scikit-learn
  - networkx
  - pandas=1.2.5
  - pandarallel
  - yaml
  - tqdm
  - matplotlib
  - plotly
  - seaborn